name: Python Linting

on:
  push:
  pull_request:

jobs:
  build:
    name: Python Linting
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: Install Python Deps
      run: python3 -m pip install flake8

    - name: Lint PicoFX
      shell: bash
      run: |
        python3 -m flake8 --show-source --ignore E501 picofx

    - name: Lint Examples
      shell: bash
      run: |
        python3 -m flake8 --show-source --ignore E501 examples

    - name: Lint Frozen Libs
      shell: bash
      run: |
        python3 -m flake8 --show-source --ignore E501 boards/*/frozen_libs
